export const RESET_STATE = 'RESET_STATE'  //重置状态
export const SET_TOKEN = 'SET_TOKEN'  //设置token
export const SET_NAME = 'SET_NAME'  //设置名称
export const SET_AVATAR = 'SET_AVATAR'  //设置avatar
export const SET_DATE = 'SET_DATE'  //设置日期
export const BI_DETAIL_BG = 'BI_DETAIL_BG' //BI头部的背景图
export const CHANGE_SETTING = 'CHANGE_SETTING'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'
export const GET_NEWS = 'GET_NEWS' //滚动消息
export const SET_AREA_INFO = 'SET_AREA_INFO' //保存省市信息    ,
export const PROVINCE_INFO = 'PROVINCE_INFO' //省市信息医院数量
export const PROVINCE_LIST = 'PROVINCE_LIST' //省市医院列表