export const RESET_STATE = 'RESET_STATE'  //重置状态
export const SET_TOKEN = 'SET_TOKEN'  //设置token
export const SET_NAME = 'SET_NAME'  //设置名称
export const SET_AVATAR = 'SET_AVATAR'  //设置avatar
export const SET_DATE = 'SET_DATE'  //设置日期
export const CHANGE_SETTING = 'CHANGE_SETTING'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'